# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a53c9105d85897c8036f8c45f580fdc7820e59febbbfe81a960684fadc77442853a8187a352d12d85ea3fd078290ccc627e6c02d052161018b2226df4287b8c3

test:
  secret_key_base: 5136f46836665b1a225309a71ea37f1963d64c2663285ebb8dd78fa83059262c7c2578f6e498365097f8a35dd67e01165be2cec8a44de8512c153af3137d0f10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
